name = "my-worker"
main = "index.js"
compatibility_date = "2023-11-21"

[vars]
# ... other variables

[[d1_databases]]
binding = "DB"
database_name = "social-app-db" # Or whatever your database name is
database_id = "d4449abe-0417-4cc0-ad0f-267368ae0d94"
